version: '3.8'

services:
  blog-pessoal-api:
    build: ./blog-pessoal-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/articles
      - QUARKUS_DATASOURCE_USERNAME=user
      - QUARKUS_DATASOURCE_PASSWORD=password

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: articles

  projeto-react:
    build: ./projeto-blog-pessoal
    ports:
      - "3000:3000"
    depends_on:
      - blog-pessoal-api
